<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\OctoType.Application\OctoType.Application.csproj" />
	  <ProjectReference Include="..\OctoType.Domain\OctoType.Domain.csproj" />
	</ItemGroup>

</Project>
